name: settings_kosmos
description: A new Flutter package project.
version: 1.0.1
homepage: none
publish_to: none
environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  dartdoc: ^6.0.0
  hooks_riverpod: ^1.0.3
  easy_localization: ^3.0.1
  get_it: ^7.2.0
  dartz: ^0.10.1
  auto_route: ^4.2.1
  flutter_svg: ^1.1.1+1
  url_launcher: ^6.1.5
  cached_network_image: ^3.2.1
  core_kosmos:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  ui_kosmos_v4:
    git:
      publish_to: none
      url: YOUR_URL
      ref: main
  firebase_storage: ^10.3.9
  image_picker: ^0.8.5+3
  firebase_auth: ^3.10.0
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  assets:
  - assets/svg/
  - assets/images/
  - assets/images/img_default_user.png
